/// Flutter icons PayMal
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PayMal
///      fonts:
///       - asset: fonts/PayMal.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PayMal {
  PayMal._();

  static const _kFontFam = 'PayMal';
  static const String _kFontPkg = null;

  static const IconData bell = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bill_payment = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cable_tv = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coupon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData couponsnmembership = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData datapack = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData donation = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData education = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData e_commerce = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electric_bill = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fortune = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift_card_light = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData healthcare = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insurance = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData internet = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loan_repayment = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData membership = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multi_datapack = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multi_topup = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData public_utility = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData register = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData single_datapack = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_account = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData topup = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData travel = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
